version: '3.8'

services:
  mysql:
    image: mysql/mysql-server
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    command: --bind-address=0.0.0.0