version: '3.9'
services:
  mysql:
    image: mysql
    cap_add:
      - SYS_NICE
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: mysql_macos
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345678
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_RANDOM_ROOT_PASSWORD: "no"
      MYSQL_ONETIME_PASSWORD: "no"
      MYSQL_INITDB_SKIP_TZINFO: "yes"
    ports:
      - '3306:3306'
    volumes:
      - ./mysql/data:/var/lib/mysql
